go get -v -u 'github.com/nsf/gocode'
go get -v -u 'github.com/alecthomas/gometalinter'
go get -v -u 'golang.org/x/tools/cmd/goimports'
go get -v -u 'golang.org/x/tools/cmd/guru'
go get -v -u 'golang.org/x/tools/cmd/gorename'
go get -v -u 'github.com/golang/lint/golint'
go get -v -u 'github.com/rogpeppe/godef'
go get -v -u 'github.com/kisielk/errcheck'
go get -v -u 'github.com/jstemmer/gotags'
go get -v -u 'github.com/klauspost/asmfmt/cmd/asmfmt'
go get -v -u 'github.com/fatih/motion'
go get -v -u 'github.com/zmb3/gogetdoc'
go get -v -u 'github.com/josharian/impl'
go get -v -u 'github.com/golang/protobuf/...'
go get -v -u 'github.com/go-sql-driver/mysql'
go get -v -u 'github.com/stretchr/testify'
go get -v -u 'github.com/cloudfoundry/gosigar'

go get       'github.com/daidodo/testa'
go get       'github.com/daidodo/overlord'
